library(readr)
library(tidyverse)
library(questionr)
library(gtsummary)

#Les thématiques des lettres : ####
df <- data_complet

df %>% tbl_summary(include = c("Schlagwörter"))

df$Briefpartner <- str_detect(df$Schlagwörter, "Briefpartner/Werk")
df$'1814' <- str_detect(df$Schlagwörter, "1814/1815")
df$'Deutschland - Politik' <- str_detect(df$Schlagwörter, "Deutschland - Politik")
df$'Musik' <- str_detect(df$Schlagwörter, "Musik")
df$'Europa - Politik' <- str_detect(df$Schlagwörter, "Europa - Politik")
df$'Krieg/Konflikt' <- str_detect(df$Schlagwörter, "Krieg/Konflikt")
df$'Belgien - Politik' <- str_detect(df$Schlagwörter, "Belgien - Politik")
df$'Frankreich - Politik' <- str_detect(df$Schlagwörter, "Frankreich - Politik")
df$'Karriere/-förderung' <- str_detect(df$Schlagwörter, "Karriere/-förderung")
df$'Deutschland - Politik' <- str_detect(df$Schlagwörter, "Deutschland - Politik")
df$'Wirtschaft/Finanzen' <- str_detect(df$Schlagwörter, "Wirtschaft/Finanzen")
df$'Reise/Mobilität' <- str_detect(df$Schlagwörter, "Reise/Mobilität")
df$'Gesundheit/Krankheit' <- str_detect(df$Schlagwörter, "Gesundheit/Krankheit")
df$'Adel' <- str_detect(df$Schlagwörter, "Adel")
df$'Alter/Jugend' <- str_detect(df$Schlagwörter, "Alter/Jugend")
df$'Freundschaft' <- str_detect(df$Schlagwörter, "Freundschaft")
df$'Ehe/Liebe' <- str_detect(df$Schlagwörter, "Ehe/Liebe")
df$'Landleben/Provinzleben' <- str_detect(df$Schlagwörter, "Landleben/Provinzleben")
df$'Erziehung/Pädagogik' <- str_detect(df$Schlagwörter, "Erziehung/Pädagogik")
df$'Reise/Mobilität' <- str_detect(df$Schlagwörter, "Reise/Mobilität")
df$'Cholera' <- str_detect(df$Schlagwörter, "Cholera")
df$'Deutschland - Wahrnehmung' <- str_detect(df$Schlagwörter, "Deutschland - Wahrnehmung")
df$'Familie/Familienrecht' <- str_detect(df$Schlagwörter, "Familie/Familienrecht")
df$'Französische Revolution' <- str_detect(df$Schlagwörter, "Französische Revolution")
df$'Tod/Trauer' <- str_detect(df$Schlagwörter, "Tod/Trauer")
df$'Gesundheit/Krankheit' <- str_detect(df$Schlagwörter, "Gesundheit/Krankheit")
df$'Landleben/Provinzleben' <- str_detect(df$Schlagwörter, "Landleben/Provinzleben")
df$'Literarisches Geschehen/Neuerscheinung' <- str_detect(df$Schlagwörter, "Literarisches Geschehen/Neuerscheinung")
df$'Theater' <- str_detect(df$Schlagwörter, "Theater")
df$'Philosophie' <- str_detect(df$Schlagwörter, "Philosophie")
df$'Medizin/ Impfung' <- str_detect(df$Schlagwörter, "Medizin/ Impfung")
df$'Reise/Mobilität' <- str_detect(df$Schlagwörter, "Reise/Mobilität")
df$'Erziehung/Pädagogik' <- str_detect(df$Schlagwörter, "Erziehung/Pädagogik")
df$'Technik/Fortschritt' <- str_detect(df$Schlagwörter, "Technik/Fortschritt")
df$'Auszeichnung/Wettbewerb' <- str_detect(df$Schlagwörter, "Auszeichnung/Wettbewerb")
df$'Gesellschaftliches Leben' <- str_detect(df$Schlagwörter, "Gesellschaftliches Leben")
df$'Militär' <- str_detect(df$Schlagwörter, "Militär")
df$'Bildende Kunst' <- str_detect(df$Schlagwörter, "Bildende Kunst")
df$'Militär' <- str_detect(df$Schlagwörter, "Militär")
df$'Botanik/Gartenkunst' <- str_detect(df$Schlagwörter, "Botanik/Gartenkunst")
df$'Rezeption' <- str_detect(df$Schlagwörter, "Constance de Salm - Rezeption")
df$'Salon/Gesellschaften' <- str_detect(df$Schlagwörter, "Salon/Gesellschaften")
df$'Emanzipation/Frau' <- str_detect(df$Schlagwörter, "Emanzipation/Frau")
df$'Post' <- str_detect(df$Schlagwörter, "Post")
df$'Prozess/Gericht' <- str_detect(df$Schlagwörter, "Prozess/Gericht")
df$'Medizin/ Impfung' <- str_detect(df$Schlagwörter, "Medizin/ Impfung")
df$'Religion/Kirche' <- str_detect(df$Schlagwörter, "Religion/Kirche")
df$'Wiener Kongress' <- str_detect(df$Schlagwörter, "Wiener Kongress")
df$'Buchhandel/Verleger' <- str_detect(df$Schlagwörter, "Buchhandel/Verleger")
df$'Gelehrte Gesellschaft' <- str_detect(df$Schlagwörter, "Gelehrte Gesellschaft")
df$'Romantik' <- str_detect(df$Schlagwörter, "Romantik")
df$'Constance de Salm - Vermarktung' <- str_detect(df$Schlagwörter, "Constance de Salm - Vermarktung")
df$livreCdS <- str_detect(df$Schlagwörter, "CdS:")

write.csv2(df, "CdS_enrichi_complet.csv")



